module CreativityBoosterQuestions
  QUESTIONS = [
    "Quelle est l'odeur de l'air dans ta rue un matin de printemps ?",
    "Quel bruit a totalement disparu de ton quotidien ?",
    "Quel est le nouveau son habituel que l'on entend dans les centres-villes ?",
    "À quoi ressemble le ciel nocturne maintenant qu'on a éteint les villes ?",
    "Qu'est-ce qu'on voit par la fenêtre d'une salle de classe ?",
    "Quelle couleur domine le paysage urbain ou rural qui t'entoure ?",
    "Quel goût a le plat le plus populaire de ton époque ?",
    "Comment les gens s'habillent-ils pour résister aux grandes chaleurs de l'été ?",
    "Quelle est la première chose que tu entends en te réveillant ?",
    "Quel est l'objet technologique le plus vieux que tu utilises encore ?",
    "Comment fait-on aujourd'hui pour s'envoyer un message urgent ?",
    "À quoi ressemble l'appareil qui a remplacé le smartphone ?",
    "Comment ton quartier produit-il son électricité ?",
    "Quel outil ou objet répares-tu le plus souvent au lieu de le jeter ?",
    "Quelle machine un peu bizarre a fait son apparition dans ta rue ?",
    "Comment récupère-t-on et stocke-t-on l'eau potable dans ton quartier ?",
    "Quel vieux savoir-faire oublié des années 1900 est redevenu indispensable ?",
    "Comment sont transportées les marchandises lourdes jusqu'à ton épicerie ?",
    "Quelle activité partages-tu obligatoirement avec tes voisins directs ?",
    "Comment s'organise une fête de quartier en 2050 ?",
    "Qui prend les décisions importantes pour l'avenir de ta commune ou de ta rue ?",
    "Quels nouveaux métiers ont fait leur apparition ?",
    "Comment les enfants passent-ils leur temps libre après l'école ?",
    "Quelle est la plus grande fierté des habitants de ton quartier ?",
    "Comment prend-on soin des personnes âgées ou isolées ?",
    "Quel sujet anime les discussions passionnées sur la place publique ce matin ?",
    "Qu'est-ce qui est devenu totalement gratuit et accessible à tous en 2050 ?",
    "Quelle règle de politesse ou d'entraide est née avec cette nouvelle société ?",
    "Quel compromis ou effort a été le plus difficile à accepter au début ?",
    "De quoi les gens ont-ils eu peur juste avant que le système ne bascule ?",
    "Quelle a été la toute première réaction des habitants quand la crise est arrivée ?",
    "Quel bâtiment, autrefois symbole du vieux monde, a été totalement transformé, et en quoi ?",
    "Quel objet du passé est aujourd'hui exposé dans les musées comme un symbole d'une époque révolue ?",
    "Quel déclic t'a fait dire : \"Ça y est, on est en train de réussir\" ?",
    "Combien d'heures par semaine consacres-tu à des tâches collectives ?",
    "Comment te déplaces-tu si tu dois aller à plus de 100 kilomètres ?",
    "Qu'est-ce qui prend beaucoup plus de temps qu'avant, et pourquoi c'est une bonne chose ?",
    "Comment s'occupe-t-on pendant un voyage qui dure plusieurs jours ?",
    "À quoi ressemble une journée de travail ordinaire en 2050 ?",
    "Comment est découpée l'année maintenant qu'on suit le rythme des saisons ?",
    "Quelle est l'activité préférée des personnes habitant dans les villes ?",
    "Comment les habitants partagent-ils leurs véhicules ou leurs moyens de transport ?",
    "Quel moyen de transport insolite vois-tu passer devant chez toi ?",
    "Si tu avais une heure de temps libre cet après-midi, où irais-tu et avec qui ?"
  ].freeze
end
